# Generated by Django 5.0.2 on 2024-03-12 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aktor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=32)),
                ('nazwisko', models.CharField(max_length=32)),
                ('filmy', models.ManyToManyField(to='main.film')),
            ],
        ),
        migrations.CreateModel(
            name='ExtraInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('czas_trwania', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('gatunek', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Horror'), (4, 'Dramat'), (0, 'Inne'), (3, 'Sci-fi'), (2, 'Komedia')], null=True)),
                ('punkty_widzow', models.PositiveSmallIntegerField(default=0)),
                ('film', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.film')),
            ],
        ),
        migrations.CreateModel(
            name='Ocena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recenzja', models.TextField(blank=True, default='')),
                ('gwiazdki', models.PositiveSmallIntegerField(default=5)),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.film')),
            ],
        ),
    ]
