# Generated by Django 5.0.2 on 2024-03-12 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_extrainfo_punkty_widzow_extrainfo_rezyser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrainfo',
            name='gatunek',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(2, 'Komedia'), (3, 'Sci-fi'), (1, 'Horror'), (4, 'Dramat'), (0, 'Inne')], null=True),
        ),
    ]
