# Generated by Django 5.0.2 on 2024-03-19 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_extrainfo_gatunek'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrainfo',
            name='gatunek',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(3, 'Sci-fi'), (4, 'Dramat'), (2, 'Komedia'), (1, 'Horror'), (0, 'Inne')], null=True),
        ),
    ]
