# Generated by Django 5.0.2 on 2024-03-26 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_extrainfo_gatunek'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrainfo',
            name='gatunek',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(3, 'Sci-fi'), (1, 'Horror'), (4, 'Dramat'), (2, 'Komedia'), (0, 'Inne')], null=True),
        ),
    ]
